### ISSUE TITLE
Is it possible to monitor temperature too ?

### ISSUE THREAD

**Issue by Snotmann** [binsoul/node-red-contrib-deye-sun-g3#2]
Hey together,

is it possible to monitor the inverter temperature too with this node ?
I was looking for a solution but until now i dont find one.

Any ideas are welcome.

Very good work by the way ... saved my 2000 lines code :)

Regards,
Snot

**Comment by binsoul** [comment]
There is a register for the temperature. It's value is above the current outside temperature in my case so it seems to be valid. I released version 0.0.5 which outputs the temperature. It's value will be null if the inverter goes offline.

**Comment by Snotmann** [comment]
Thanks a lot ... its working fine. Thousand thanks for saving me so much trouble :-*

Very good work this node will save a lot of people a lot of work !

**Comment by binsoul** [comment]
You are welcome. :)
