### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by makabar** [binsoul/node-red-contrib-deye-sun-g3#8]
its not working since forced upgrade to MW3_SSL_5408_1.0B firmware.
maybe deye changed something on modbus

**Comment by tossa-fan** [comment]
Hi,

here the same issue with MW3_SSL_5408_1.0B: error: message: "Frame does not contain a valid Modbus RTU frame."

Can you look into it?

Best regards, Jorge

**Comment by fschaefer** [comment]
It looks like the readable registers have changed with the firmware update. 

https://github.com/binsoul/node-red-contrib-deye-sun-g3/blob/master/src/deye-sun-g3/Action/UpdateAction.ts#L41C10-L41C37

Change `const lastRegister = 0x0080` to `const lastRegister = 0x007f` and it works again.

As a temporary fix until the library is updated: Typically you can find this in `node_modules` of your installation at `~/.node-red/node_modules/@binsoul/node-red-contrib-deye-sun-g3/dist/deye-sun-g3/Action/UpdateAction.js` in the `execute()` method. Change `0x0080` to `0x007f` and restart node-red.

**Comment by tossa-fan** [comment]
@fschaefer: thank you very much, it works :-)

**Comment by binsoul** [comment]
@fschaefer, thank you very much. I can confirm that it works. Published a new version including the fix.
